<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WorktimesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('worktimes')->insert([
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-1',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-2',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-3',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-4',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-5',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-6',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-7',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-8',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-9',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-10',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-11',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-12',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-13',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-14',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-15',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-16',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-17',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-18',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-19',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-20',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-21',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-22',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-23',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-24',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-25',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-26',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-27',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-28',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-29',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],            [
				'member_id'=> '1001',
				'work_date'=> '2023-9-30',
				'work_start' => '8:30',
				'work_end' => '17:15',
				'work_type'=> '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
            ],
        ]);
	}
}
